global:
  path: /home/samuelr/projects/WindViViT/project
  raw_data_path: data/raw
  processed_data_path: data/processed
  constants_path: data/constants
  checkpoints_path: checkpoints
  reports_path: reports
preprocessing: 
  upper_var_names: ['time', 'u', 'v', 'q', 't', 'd', 'z', 'w', 'vo']
  surface_var_names: ['time', 'u100', 'v100', 'u10', 'v10', 'd2m', 't2m', 'z', 'msl', 'i10fg']
  limits:
    latitude:  [10, 28]
    longitude: [18, 36]
    levels: [0, 9]
    years: [1990, 2017]
barajas:
  latitude: 40.5
  longitude: -3.5
model:
  image_size_3d: [9, 18, 18, 8]
  patch_size_3d: [3, 6, 6]
  image_size_2d: [18, 18, 9]
  patch_size_2d: [6, 6]
  dim: 1024 #512 / 768 / 1024
  depth: 24 #6 / 12 / 24
  heads: 16 #6 / 12 / 16
  dim_head: 64 # 32 / 64 / 64
  dropout: 0.1
  emb_dropout: 0.1
  reconstr_dropout: 0.1
  scale_dim: 4 #2 / 4 / 4
train:
  batch_size: 32
  iters_to_accumulate: 1
  sequence_length: 6 # seq_len * num_patches = 256 (6)
  learning_rate: 0.0001
  warmup_ratio: 0 
  epochs: 50
  train_split: [1990, 2015]
  val_split: [2016]
  test_split: [2017]
  prefetch: 2
  workers: 2
  log_mid_loss: True
  save_model: True
  model_name: model_3
plots:
  pred_vs_true: True

