global:
  path: /home/windgust/workspace/project
  raw_data_path: data/raw
  processed_data_path: data/processed
  constants_path: data/constants
preprocessing: 
  upper_var_names: ['time', 'u', 'v', 'q', 't', 'd', 'z', 'w', 'vo']
  surface_var_names: ['time', 'u100', 'v100', 'u10', 'v10', 'd2m', 't2m', 'z', 'msl']
  limits:
    longitude: [18, 35]
    latitude:  [10, 28]
    levels: [0, 8]
barajas:
  latitude: 40.5
  longitude: -3.5
