global:
  path: /home/samuelr/projects/WindViViT/project
  raw_data_path: data/raw
  processed_data_path: data/processed
  data_file: real_data.hdf5 # real_data.hdf5 / data.hdf5
  constants_path: data/constants
  real_data_path: data/real
  checkpoints_path: checkpoints
  reports_path: reports
preprocessing: 
  upper_var_names: ['time', 'u', 'v'] #['time', 'u', 'v', 'q', 't', 'd', 'z', 'w', 'vo']
  surface_var_names: ['time', 'u10', 'v10'] #['time', 'u100', 'v100', 'u10', 'v10', 'd2m', 't2m', 'z', 'msl', 'i10fg']
  limits:
    latitude:  [9, 34]
    longitude: [12, 27]
    levels: [0, 9]
    years: [1979, 2023]
model:
  image_size_2d: [25, 15, 2]
  patch_size_2d: [5, 5]
  dim: 768 #512 / 768 / 1024
  depth: 12 #6 / 12 / 24
  heads: 12 #6 / 12 / 16
  dim_head: 64 # 32 / 64 / 64
  dropout: 0.1
  emb_dropout: 0.1
  scale_dim: 4 #2 / 4 / 4
  pretrained: model_10_pretrained # False
  active_indices: False #[2,6,13]
train:
  batch_size: 64
  iters_to_accumulate: 1
  sequence_length: 32 # seq_len * num_patches = 256 (6)
  learning_rate: 0.00001 #0.0001 / 0.00001
  warmup_ratio: 0
  epochs: 70
  train_split: [2002, 2009] #[[1979,2009],[2012,2023]]
  val_split: [2010]
  test_split: [2011]
  prefetch: 2
  workers: 2
  log_mid_loss: True
  save_model: True
  model_name: model_12_real
plots:
  pred_vs_true: True
real_data:
  years: [2002, 2012]
  locations:
    pena:
      latitude: 40.25
      longitude: -6.75
    jara:
      latitude: 37.0
      longitude: -5.0
    minon:
      latitude: 42.5
      longitude: -3.75
    barajas:
      latitude: 40.5
      longitude: -3.5
