global:
  path: /home/windgust/workspace/project
  raw_data_path: data/raw
  processed_data_path: data/processed
  constants_path: data/constants
  train_data_path: data/train
  checkpoints_path: checkpoints
  reports_path: reports
preprocessing: 
  upper_var_names: ['time', 'u', 'v', 'q', 't', 'd', 'z', 'w', 'vo']
  surface_var_names: ['time', 'u100', 'v100', 'u10', 'v10', 'd2m', 't2m', 'z', 'msl', 'i10fg']
  limits:
    latitude:  [10, 27]
    longitude: [18, 35]
    levels: [0, 8]
barajas:
  latitude: 40.5
  longitude: -3.5
model:
  image_size_3d: [9, 18, 18, 8]
  patch_size_3d: [3, 6, 6]
  image_size_2d: [18, 18, 9]
  patch_size_2d: [6, 6]
  output_dim: [10, 18, 18, 2]
  dim: 512 #512 / 768
  depth: 6 #6 / 12
  heads: 6 #6 / 12
  dim_head: 32 # 32 / 64
  dropout: 0.1
  emb_dropout: 0.1
  reconstr_dropout: 0.1
  scale_dim: 2 #2 / 4
train:
  batch_size: 16
  iters_to_accumulate: 2
  sequence_length: 6 # seq_len * num_patches = 256
  learning_rate: 0.001
  warmup_ratio: 0.06 
  epochs: 30
  train: 0.7
  validation: 0.15
  test: 0.15
  log_mid_loss: True
  save_model: True
  model_name: model_2
plots:
  pred_vs_true: True

